name: molecule_scanner
channels:
  - conda-forge
dependencies:
  - python 3.9
  - notebook
  - jupyter
  - numpy
  - pandas
  - matplotlib
  - dash
  - plotly
  - pandoc
  - pip
  - dash
  - dash-bio
  - setuptools 65.6.3
  - pip:
      - git+https://github.com/GwydionJon/py2sambvca
      - joblib
      - waitress
      - xyz-py
