name: molecule_scanner
channels:
  - conda-forge
dependencies:
  - python 3.9
  - notebook
  - jupyter
  - numpy
  - pandas
  - matplotlib
  - jupyterlab-dash
  - jupyter-dash
  - dash
  - plotly
  - pandoc
  - pip
  - pip:
      - py2sambvca
      - joblib
      - git+https://github.com/GwydionJon/OC-Forschi
